baseURL = 'https://cabbaken.github.io/'
languageCode = 'en-us'
title = "Cabbaken's Blog"
theme = 'void'


# Social media links
[params]
  [params.social]
    github = "https://github.com/cabbaken"
    telegram = "https://twitter.com/yourusername"
    email = "cabbaken@outlook.com"
  [params.avatar]
    url = "https://avatars.githubusercontent.com/u/62502537?v=4"

# Main menu
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 50